export const SEARCH_TYPE = {
  SET_SEARCH: "search/SET_SEARCH",

  IS_FUZZY_SEARCH: "search/IS_FUZZY_SEARCH",
  FUZZY_SEARCH: "search/FUZZY_SEARCH",
  FUZZY_SEARCH_ARRAY: "search/FUZZY_SEARCH_ARRAY",

  FETCH_FUZZY_SEARCH_ARRAY_START: "search/FETCH_FUZZY_SEARCH_ARRAY_START",
  FETCH_FUZZY_SEARCH_ARRAY_SUCCESS: "search/FETCH_FUZZY_SEARCH_ARRAY_SUCCESS",
  FETCH_FUZZY_SEARCH_ARRAY_FAILED: "search/FETCH_FUZZY_SEARCH_ARRAY_FAILED",
};
