export const SEARCH_TYPE = {
  SET_SEARCH: "search/SET_SEARCH",
  IS_CLEARED_SEARCH: "search/IS_CLEARED_SEARCH",
  IS_FUZZY_SEARCH: "search/IS_FUZZY_SEARCH",
  FUZZY_SEARCH: "search/FUZZY_SEARCH",
  FUZZY_SEARCH_ARRAY: "search/FUZZY_SEARCH_ARRAY",
  IS_LOADING: "search/IS_LOADING",
};
