export const JOBS_TYPE = {
  FETCH_JOBS_START: "jobs/FETCH_JOBS_START",
  FETCH_HITS_JOBS_START: "jobs/FETCH_HITS_JOBS_START",
  FETCH_SEARCH_JOBS_START: "jobs/FETCH_SEARCH_JOBS_START",
  FETCH_JOBS_SUCCESS: "jobs/FETCH_JOBS_SUCCESS",
  FETCH_JOBS_FAILED: "jobs/FETCH_JOBS_FAILED",
  FETCH_HITS_JOBS_SUCCESS: "jobs/FETCH_HITS_JOBS_SUCCESS",
};
